version: '3.4'

services:
  patternfly-react-seed:
    image: patternfly-react-seed
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js